apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-tools
spec:
  generators:
  - git:
      repoURL: https://github.com/Ryad3/appset_values_pipe
      revision: main
      files:
      - path: Tools/*.yaml
  template:
    metadata:
      name: '{{ `{{name}}` }}'  # ← Backticks pour échapper
    spec:
      project: admin
      source:
        helm:
          valueFiles:
          - values.yaml
          values: |
            {{ `{{values}}` }}  # ← Backticks pour échapper
        repoURL: https://github.com/Ryad3/appset_values_pipe
        path: Tools/charts/{{ `{{helm_chart}}` }}  # ← Backticks pour échapper
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{ `{{namespace}}` }}'  # ← Backticks pour échapper
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=false
        - CreateNamespace=false
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
