apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-tools
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Ryad3/appset_values_pipe
      revision: main
      files:
      - path: config/*.yaml
  template:
    metadata:
      name: '{{"{{"}}.name{{"}}"}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
          values: |-
            {{"{{"}} toYaml .values {{"}}"}}
        repoURL: https://github.com/Ryad3/appset_values_pipe
        path: 'Tools/charts/{{"{{"}}.helm_chart{{"}}"}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{"{{"}}.namespace{{"}}"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=false
        - CreateNamespace=false
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
