{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "buildkitd.fullname" . }}-network-policy
  labels:
    {{- include "buildkitd.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "buildkitd.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- range .Values.networkPolicy.ingress.namespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      {{- end }}
{{- end }}
