apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildkitd.fullname" . }}
  labels:
    {{- include "buildkitd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 1234
      targetPort: 1234
      protocol: TCP
      name: buildkit
  selector:
    {{- include "buildkitd.selectorLabels" . | nindent 4 }}
